name: 'Scalr Terraform CLI'
description: 'Installs Terraform CLI and configures it with Scalr.'
author: 'Scalr'
inputs:
  scalr_hostname:
    description: 'The hostname of a Scalr install. Example: username.scalr.io.'
    required: true
  scalr_token:
    description: 'The API token to use.'
    required: true
  terraform_version:
    description: 'The version of Terraform CLI to install. Should match the version set in your Scalr Workspace.'
    required: true
  terraform_wrapper:
    description: 'Whether or not to install a wrapper to wrap subsequent calls of the `terraform` binary and expose its STDOUT, STDERR, and exit code as outputs named `stdout`, `stderr`, and `exitcode` respectively. Defaults to `true`.'
    default: 'true'
    required: false
  terraform_output:
    description: 'Export Terraform output variables as Action output variables.'
    default: false
    required: false
runs:
  using: 'node16'
  main: 'dist/terraform/index.js'
branding:
  icon: 'terminal'
  color: 'red'