name: Move tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to move'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - v1
      version:
        description: 'Version'
        default: 'v0.0.0'
        required: true 
        type: string

jobs:
  release:
    name: Move tag
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push change to repo
        run: |
          git config --global user.email "github@scalr.com"
          git config --global user.name "Github Action"
          HASH=$(git rev-parse ${{ inputs.version }})
          git tag -fa -m "Move tag to $HASH" ${{ inputs.tag }} $HASH
          git push -f origin ${{ inputs.tag }}
