name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]    

    steps:
      - uses: Scalr/scalr-action@test
        with:
          terraform_version: '1.3.7'
          scalr_token: 'test-token'
          scalr_hostname: 'test.scalr.io'

      - id: version
        name: Terraform version
        run: terraform -v

      - id: cli-version
        name: Scalr CLI version
        run: scalr -version
