name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]    

    steps:
      - uses: Scalr/scalr-action@test
        with:
          terraform_version: '1.2.1'
          scalr_token: 'test-token'
          scalr_hostname: 'test.scalr.io'

      - id: version
        name: Version
        run: terraform -v

      - name: Print output
        run: echo '${{ steps.version.outputs.stdout }}'